include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    constant_identifier_names: false
    library_prefixes: false
    avoid_renaming_method_parameters: false
    unawaited_futures: true
    prefer_interpolation_to_compose_strings: false
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false
    unrelated_type_equality_checks: true

analyzer:
  errors:
    unrelated_type_equality_checks: error
    collection_methods_unrelated_type: error
    unawaited_futures: error
    unused_element: ignore
